--- #YAML:1.0
name:               Data-Visitor
version:            0.25
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Any::Moose:        0.09
    namespace::clean:  0.08
    Task::Weaken:      0
    Test::MockObject:  1.04
    Test::More:        0
    Test::use::ok:     0
    Tie::ToObject:     0.01
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
