---
name: Data-Visitor
version: 0.04
author:
  - 'Yuval Kogman <nothingmuch@woobling.org>'
abstract: Visitor style traversal of Perl data structures
license: perl
requires:
  perl: '>= 5.008'
build_requires:
  Class::Accessor: 0
  Test::MockObject: 1.04
  Test::More: 0
  Test::use::ok: 0
provides:
  Data::Visitor:
    file: lib/Data/Visitor.pm
    version: 0.04
  Data::Visitor::Callback:
    file: lib/Data/Visitor/Callback.pm
generated_by: Module::Build version 0.2611
