--- #YAML:1.0
name:                Data-Visitor
version:             0.18
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Data::Alias:                   0
    Mouse:                         0.04
    namespace::clean:              0.08
    Task::Weaken:                  0
    Test::MockObject:              1.04
    Test::More:                    0
    Test::use::ok:                 0
    Tie::ToObject:                 0.01
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
